artifact_location: file:///Users/rejur/Documents/Lilaq/Training/MLOps/Module 1/mlops_m2_lab1/mlruns/0
creation_time: 1767949734159
experiment_id: '0'
last_update_time: 1767949734159
lifecycle_stage: active
name: Default
