artifact_uri: file:///Users/rejur/Documents/Lilaq/Training/MLOps/Module 1/mlops_m2_lab1/mlruns/327667224824638060/41ba190848274e02b46f4fffaa401c7a/artifacts
end_time: 1768207790150
entry_point_name: ''
experiment_id: '327667224824638060'
lifecycle_stage: active
run_id: 41ba190848274e02b46f4fffaa401c7a
run_name: iris-random-forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1768207788755
status: 3
tags: []
user_id: rejur
