artifact_location: file:///Users/rejur/Documents/Lilaq/Training/MLOps/Module 1/mlops_m2_lab1/mlruns/327667224824638060
creation_time: 1767949734162
experiment_id: '327667224824638060'
last_update_time: 1767949734162
lifecycle_stage: active
name: iris_classification
