artifact_uri: file:///Users/rejur/Documents/Lilaq/Training/MLOps/Module 1/mlops_m2_lab1/mlruns/327667224824638060/83b4ae3862ca475397e24d8fcf166b9c/artifacts
end_time: 1768207791403
entry_point_name: ''
experiment_id: '327667224824638060'
lifecycle_stage: active
run_id: 83b4ae3862ca475397e24d8fcf166b9c
run_name: iris-random-forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1768207790156
status: 3
tags: []
user_id: rejur
