artifact_uri: file:///Users/rejur/Documents/Lilaq/Training/MLOps/Module 1/mlops_m2_lab1/mlruns/327667224824638060/51abfeeeda8146ce9b5b041fecd85133/artifacts
end_time: 1768207642425
entry_point_name: ''
experiment_id: '327667224824638060'
lifecycle_stage: active
run_id: 51abfeeeda8146ce9b5b041fecd85133
run_name: iris-random-forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1768207641168
status: 3
tags: []
user_id: rejur
